Frontend init
smknaqvi/canvas-teams-lti pull request #15
Opened 2021-01-08 09:09 UTC by smknaqvi

# Description
Adding react-gatsby app
# Closes issue(s)
closes #3 
# How to test / repro

# Screenshots

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have tested this code
- [ ] I have updated the Readme

# Other comments
todo 
[ ] add jest
[ ] add netlify deploy
[ ] run tests on pull request

2021-01-08 20:23 UTC, ma-anwar commented on frontend/src/pages/index.tsx
> +const IndexPage = () => <div>Hello World {a}</div>
I'm getting an error trying to build, 

```
Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  1 | import React from "react"
  2 | 
> 3 | const IndexPage = () => <div>Hello World {a}</div>
    |                         ^
  4 | 
  5 | export default IndexPage
  6 | 


  WebpackError: ReferenceError: a is not defined
  
  - index.tsx:3 
    src/pages/index.tsx:3:25
```

2021-01-08 20:25 UTC, ma-anwar requested changes
Will wait for further changes so I can build.

2021-01-09 02:06 UTC, smknaqvi commented on frontend/src/pages/index.tsx
> +const IndexPage = () => <div>Hello World {a}</div>
oopsies

2021-01-09 02:06 UTC, smknaqvi commented on frontend/src/pages/index.tsx
> +const IndexPage = () => <div>Hello World {a}</div>
> Will wait for further changes so I can build.

i ended up killing the .vscode config... turns out its no good in subdirectories, only works for whole proj so it wasn't actually doing anything heh

2021-01-09 02:13 UTC, merged