Backend configuration
smknaqvi/canvas-teams-lti pull request #9
Opened 2021-01-07 05:47 UTC by ma-anwar

# Description
Configure back end to receive token from Canvas instance 

# Closes issue(s)
Closes #4 back end stack initial commit
# How to test / repro

# Screenshots

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have tested this code
- [ ] I have updated the Readme

# Other comments

2021-01-07 06:04 UTC, smknaqvi requested changes
looking good so far

gave some suggestions

we should open up some issues for follow ups
1. types audit - we can make better use of typescript probs
2. env vars, need to consider how to proceed
3. db set up gotta design it and then add it

2021-01-07 06:04 UTC, smknaqvi commented on backend/package.json
> +  "name": "whatabyte-portal",
i think this name from another boilerplate? maybe we can call it `canvas-teams-server` for now? or if you have better name that works too

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +// dotenv.config();
assuming we gonna do this later? lets open an issue for it if so

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +});
this is fine for now, gonna be changed later, maybe lets put a to do here as well

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +app.post("/", (req: Request, res: Response) => {
can we make a routes folder, and put the oauth routes in a seprate file, and connect it from there? including the following endpoints

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +  const redirectURL = new URL("http://localhost:8080/login/oauth2/auth");
we shouldn't hardcode localhost:8080, for now we can put it in a constant, but eventually we will want to figure out how to get the url, maype its passed into the endpoint? if it is then we should use that

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +  }).then((res) => console.log(res));
lets put a todo with the console log here as well,

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +app.get("/done", (req: Request, res: Response) => {
can we rename `/done` to `oauth_complete`, seems more descriptive

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +  console.log(`Listening to requests on http://localhost:${port}`);
probs dont wanna hardcode localhost here, but i suppose this goes in the env file actually, same with the port #

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/strategy.ts
> +    consumerSecret:
can you make a constants file and put these into constants so they can be used across the app for now, i guess eventually this would be in the db per customer but for this pr can have it as constants

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/strategy.ts
> +import { AnyPtrRecord } from "dns";
what's this?

2021-01-07 06:04 UTC, smknaqvi commented on backend/src/index.ts
> +const CLIENT_SECRET =
we can put these into a `constants.js` file for now so they can be used throughout the app

2021-01-07 21:02 UTC, ma-anwar commented on backend/src/index.ts
> +// dotenv.config();
Issue opened

2021-01-07 21:02 UTC, ma-anwar commented on backend/src/index.ts
> +});
Added todo

2021-01-07 21:02 UTC, ma-anwar commented on backend/src/index.ts
> +app.post("/", (req: Request, res: Response) => {
See latest commit

2021-01-07 21:05 UTC, ma-anwar commented on backend/src/index.ts
> +  const redirectURL = new URL("http://localhost:8080/login/oauth2/auth");
See latest commit, added to constants. Will determine if we can get it from it being passed to endpoint however anyone could query endpoint. May add a check for issuer being canvas and then redirect. For now I have just extracted to constants. Can I make this an issue for the future?

2021-01-07 21:05 UTC, ma-anwar commented on backend/src/index.ts
> +app.get("/done", (req: Request, res: Response) => {
See latest commit for new endpoint names.

2021-01-07 21:05 UTC, ma-anwar commented on backend/src/index.ts
> +  console.log(`Listening to requests on http://localhost:${port}`);
Extracted to Constants

2021-01-07 21:06 UTC, ma-anwar commented on backend/src/strategy.ts
> +import { AnyPtrRecord } from "dns";
Mistaken import

2021-01-07 21:07 UTC, ma-anwar commented
Thanks for feedback, take a look at latest commit and let me know what you think.

2021-01-07 21:48 UTC, smknaqvi approved these changes
just a few more small things, but after those LGTM, good to merge

also i get Request failed with status code 422 instead of the token gonna keep debugging y it does that

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +      url: "http://localhost:8080/login/auth2/token",
nit can we move the localhost to a constant for now

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +    const redirectURL = new URL("http://localhost:8080/login/oauth2/auth");
nit can we move the localhost to a constant for now

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/index.ts
> +app.use("/auth", authRoutes);
lets put a comment above this like `// Routes`

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/index.ts
> +app.use(bodyParser.json());
lets put a comment above this like `// middleware`

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +import axios from "axios";
nit - for convenience (in case anything else ends up being called auth since its a common word) can we use the convention to always call our routes like `authRoutes` i.e. `<insert name>Routes`

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +// export {router};
nit - remove

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/index.ts
> +passport.serializeUser((user, done) => {
missing types

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/index.ts
> +passport.serializeUser((user, done) => {
can u install the eslint plugin, it will give red squiglys so u can see

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/index.ts
> +passport.deserializeUser((id: any, done) => {
missing types

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +  .route("/init")
rationale on not splitting into 2 routes?

2021-01-07 21:48 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +    const redirectURL = new URL("http://localhost:8080/login/oauth2/auth");
just curious

2021-01-08 01:18 UTC, ma-anwar commented on backend/src/routes/auth.ts
> +  .route("/init")
Split into two routes in latest commit

2021-01-08 01:27 UTC, smknaqvi approved these changes
lgtm

2021-01-08 01:27 UTC, smknaqvi commented on backend/src/routes/auth.ts
> +      url: "http://localhost:8080/login/auth2/token",
also forgot the o hehe

2021-01-08 01:32 UTC, merged